// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/protocol/message.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_SYSTEM  MessageType = 0 // 系统广播（上线/下线）
	MessageType_CHAT    MessageType = 1 // 群聊消息
	MessageType_PRIVATE MessageType = 2 // 私聊消息
	MessageType_WHO     MessageType = 3 // 查询在线用户
	MessageType_RENAME  MessageType = 4 // 修改用户名
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "SYSTEM",
		1: "CHAT",
		2: "PRIVATE",
		3: "WHO",
		4: "RENAME",
	}
	MessageType_value = map[string]int32{
		"SYSTEM":  0,
		"CHAT":    1,
		"PRIVATE": 2,
		"WHO":     3,
		"RENAME":  4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_protocol_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_message_proto_rawDescGZIP(), []int{0}
}

// 聊天消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"` // 消息类型
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`                            // 发送者（服务端填充）
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`                                // 接收者（私聊用）
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                      // 消息内容（可包含任意字符）
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 时间戳（服务端填充）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_protocol_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_protocol_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_SYSTEM
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_protocol_message_proto protoreflect.FileDescriptor

const file_internal_protocol_message_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocol/message.proto\x12\bprotocol\"\x90\x01\n" +
	"\aMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.protocol.MessageTypeR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp*E\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x00\x12\b\n" +
	"\x04CHAT\x10\x01\x12\v\n" +
	"\aPRIVATE\x10\x02\x12\a\n" +
	"\x03WHO\x10\x03\x12\n" +
	"\n" +
	"\x06RENAME\x10\x04B\x1cZ\x1aimsystem/internal/protocolb\x06proto3"

var (
	file_internal_protocol_message_proto_rawDescOnce sync.Once
	file_internal_protocol_message_proto_rawDescData []byte
)

func file_internal_protocol_message_proto_rawDescGZIP() []byte {
	file_internal_protocol_message_proto_rawDescOnce.Do(func() {
		file_internal_protocol_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_message_proto_rawDesc), len(file_internal_protocol_message_proto_rawDesc)))
	})
	return file_internal_protocol_message_proto_rawDescData
}

var file_internal_protocol_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protocol_message_proto_goTypes = []any{
	(MessageType)(0), // 0: protocol.MessageType
	(*Message)(nil),  // 1: protocol.Message
}
var file_internal_protocol_message_proto_depIdxs = []int32{
	0, // 0: protocol.Message.type:type_name -> protocol.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protocol_message_proto_init() }
func file_internal_protocol_message_proto_init() {
	if File_internal_protocol_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_message_proto_rawDesc), len(file_internal_protocol_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_message_proto_goTypes,
		DependencyIndexes: file_internal_protocol_message_proto_depIdxs,
		EnumInfos:         file_internal_protocol_message_proto_enumTypes,
		MessageInfos:      file_internal_protocol_message_proto_msgTypes,
	}.Build()
	File_internal_protocol_message_proto = out.File
	file_internal_protocol_message_proto_goTypes = nil
	file_internal_protocol_message_proto_depIdxs = nil
}
